### ISSUE TITLE
1 command install script for noobs?

### ISSUE THREAD

**Issue by slrgt** [Merlin04/superbird-webapp#4]
Now that CarThing is officially being bricked by Spotify there are many people searching for how they can continue to use their Car Thing. Could there be a script made so people who don't know much about technology can install this to continue using their Car Thing?

**Comment by Merlin04** [comment]
Unfortunately this repo won't make Car Thing continue to work after Spotify bricks it, since Car Thing depends on the Spotify app having support for it. This repo is more intended for developers who want to mod the Car Thing software or people who want it to work without premium. 

Once a solution exists to make it continue working, we'll definitely make sure to have an easy to follow guide!
